export const VALSET_DRIVER_ABI = [
  {
    type: 'function',
    name: 'getConfigAt',
    inputs: [
      {
        name: 'timestamp',
        type: 'uint48',
        internalType: 'uint48',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IValSetDriver.Config',
        components: [
          { name: 'numAggregators', type: 'uint208', internalType: 'uint208' },
          { name: 'numCommitters', type: 'uint208', internalType: 'uint208' },
          {
            name: 'votingPowerProviders',
            type: 'tuple[]',
            internalType: 'struct IValSetDriver.CrossChainAddress[]',
            components: [
              { name: 'chainId', type: 'uint64', internalType: 'uint64' },
              { name: 'addr', type: 'address', internalType: 'address' },
            ],
          },
          {
            name: 'keysProvider',
            type: 'tuple',
            internalType: 'struct IValSetDriver.CrossChainAddress',
            components: [
              { name: 'chainId', type: 'uint64', internalType: 'uint64' },
              { name: 'addr', type: 'address', internalType: 'address' },
            ],
          },
          {
            name: 'settlements',
            type: 'tuple[]',
            internalType: 'struct IValSetDriver.CrossChainAddress[]',
            components: [
              { name: 'chainId', type: 'uint64', internalType: 'uint64' },
              { name: 'addr', type: 'address', internalType: 'address' },
            ],
          },
          { name: 'maxVotingPower', type: 'uint256', internalType: 'uint256' },
          { name: 'minInclusionVotingPower', type: 'uint256', internalType: 'uint256' },
          { name: 'maxValidatorsCount', type: 'uint208', internalType: 'uint208' },
          { name: 'requiredKeyTags', type: 'uint8[]', internalType: 'uint8[]' },
          {
            name: 'quorumThresholds',
            type: 'tuple[]',
            internalType: 'struct IValSetDriver.QuorumThreshold[]',
            components: [
              { name: 'keyTag', type: 'uint8', internalType: 'uint8' },
              { name: 'quorumThreshold', type: 'uint248', internalType: 'uint248' },
            ],
          },
          { name: 'requiredHeaderKeyTag', type: 'uint8', internalType: 'uint8' },
          { name: 'verificationType', type: 'uint32', internalType: 'uint32' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    inputs: [],
    name: 'getCurrentEpoch',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCurrentEpochDuration',
    outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCurrentEpochStart',
    outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getNextEpoch',
    outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getNextEpochDuration',
    outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getNextEpochStart',
    outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    type: 'function',
    name: 'getEpochStart',
    inputs: [{ name: 'epoch', type: 'uint48', internalType: 'uint48' }],
    outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
    stateMutability: 'view',
  },
  {
    inputs: [{ name: 'timestamp', type: 'uint48', internalType: 'uint48' }],
    name: 'getEpochIndex',
    outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'epoch', type: 'uint48', internalType: 'uint48' }],
    name: 'getEpochDuration',
    outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SUBNETWORK',
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NETWORK',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
